name: Build and test
on: null
jobs:
    name: Generate build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - run: yarn run build firefox


      # Release packages
      # --------------------------------------        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          files: |
            ../../packages/motrix-webextension.*.firefox.xpi.zip            
