name: Build and test
on: null
jobs:
    name: Generate build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - run: yarn run build firefox
      - name: Action Release
  uses: yakuhzi/release-asset@v1.2.3
  with:
    # File to upload to the release
    file: 
     ../../packages/motrix-webextension.*.firefox.xpi.zip
